name: Sync to Azure Repo

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (change to your branch if needed)

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Azure repository as a remote
        run: git remote add azure https://mshubhashree:${{ secrets.AZURE_PAT }}@dev.azure.com/chatapppipelinetask/chatapp/_git/chatapp
       

      - name: Fetch latest changes from Azure
        run: git fetch azure

      - name: Merge changes from GitHub to Azure
        run: |
          git checkout main  # Or change to your branch
          git merge origin/main
          git push azure main
