name: Sync to Azure Repo

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Azure repository as a remote
        run: |
          git remote add azure https://mshubhashree:${{ secrets.AZURE_PAT }}@dev.azure.com/chatapppipelinetask/chatapp%28CICD%29/_git/chatapp%28CICD%29

      - name: Fetch latest changes from Azure
        run: git fetch azure

      - name: Merge remote changes
        run: |
          git checkout main
          git pull azure main --rebase || git merge azure/main  # Try rebase first, fallback to merge if necessary

      - name: Push changes to Azure
        run: git push azure main
